### ISSUE TITLE
Automine error

### ISSUE THREAD

**Issue by JihemNC** [ogame-tbot/TBot#13]
Hi
Using univers 181 and language FR
[Info] [Defender] [08/03/2021 17:11:57] - Your empire is safe
[Info] [Defender] [08/03/2021 17:11:57] - Next check at 08/03/2021 17:13:19
[Info] [Brain] [08/03/2021 17:11:58] - Next BuyOfferOfTheDay check at 08/03/2021 21:35:50
[Info] [Brain] [08/03/2021 17:12:12] - Running automine
[Error] [Brain] [08/03/2021 17:12:16] - AutoMine Exception: Sequence contains no matching element
[Warning] [Brain] [08/03/2021 17:12:16] - Stacktrace:    at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Tbot.Includes.Helpers.ParseCelestialsList(Object source, List`1 currentCelestials)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Tbot.Program.AutoMine(Object state)
[Info] [Brain] [08/03/2021 17:12:18] - Next AutoMine check at 08/03/2021 17:28:50
[Info] [Brain] [08/03/2021 17:12:29] - Repatriating resources...
[Warning] [Brain] [08/03/2021 17:12:35] - Unable to complete repatriate: Sequence contains no matching element
[Warning] [Brain] [08/03/2021 17:12:35] - Stacktrace:    at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Tbot.Includes.Helpers.ParseCelestialsList(Object source, List`1 currentCelestials)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Tbot.Program.AutoRepatriate(Object state)
[Info] [Brain] [08/03/2021 17:12:40] - Next repatriate check at 08/03/2021 18:09:52
[Info] [Expeditions] [08/03/2021 17:12:50] - Next check at 08/03/2021 17:18:22
[Info] [Brain] [08/03/2021 17:12:55] - Checking capacity...
[Error] [Brain] [08/03/2021 17:13:01] - Unable to complete autocargo: Sequence contains no matching element
[Warning] [Brain] [08/03/2021 17:13:01] - Stacktrace:    at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Tbot.Includes.Helpers.ParseCelestialsList(Object source, List`1 currentCelestials)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Tbot.Program.AutoBuildCargo(Object state)
[Info] [Brain] [08/03/2021 17:13:06] - Next capacity check at 08/03/2021 20:26:26
[Info] [Defender] [08/03/2021 17:13:20] - Checking attacks...
[Info] [Defender] [08/03/2021 17:13:24] - Your empire is safe
[Info] [Defender] [08/03/2021 17:13:24] - Next check at 08/03/2021 17:27:10

**Comment by kokiddp** [comment]
parsecelestials failed, you probably have an invalid coordinate in automine origin and in autorepatriate exclude list or target

**Comment by JihemNC** [comment]
Thank's, fixed

And working perfect with mac arm m1 and core 5

**Comment by JihemNC** [comment]
How to disable exclusion ?
![image](https://user-images.githubusercontent.com/78060667/128085655-1537f8cc-d609-4dc7-b41b-f387c6325cce.png)
Want to mine all my planet .
Ty

**Comment by kokiddp** [comment]
just put an empty array in "Exclude"
like this

`"Exclude": [],`
