### ISSUE TITLE
problem with lifeform automine

### ISSUE THREAD

**Issue by Deenayd** [ogame-tbot/TBot#133]
Hello,

Not sure how to debug, but this started to happen after I started using lifeforms in few next planets:

```
[Error] [Brain] [29.10.2022 06:01:30] - Lifeform AutoMine Exception: An error has occurred: Status: error - Message: invalid ogameID
[Warning] [Brain] [29.10.2022 06:01:30] - Stacktrace:    at Tbot.Services.OgamedService.GetPrice(LFBuildables buildable, Int64 levelOrQuantity) in *****\source\repos\TBot2\TBot\Services\OgamedService.cs:line 923
   at Tbot.Includes.Helpers.GetNextLFBuildingToBuild(Celestial planet, Int32 maxPopuFactory, Int32 maxFoodFactory, Int32 maxTechFactory) in *****\source\repos\TBot2\TBot\Includes\Helpers.cs:line 2018
   at Tbot.Program.LifeformAutoMine(Object state) in *****\source\repos\TBot2\TBot\Program.cs:line 4182
```

**Comment by Antho59** [comment]
hello,

can you check into logs which lf buildings it tried to build ?

**Comment by Deenayd** [comment]
Well... no.

But it was when I wanted to do few tests with Mechs. I have already switched away from Mechs (not using them) and problem disappeared.
