### ISSUE TITLE
Problem with manual captcha solving

### ISSUE THREAD

**Issue by SebastianKumor** [ogame-tbot/TBot#158]
I usually get error - `+02:00 12 WRN Tbot] [Test] Unable to login ("403 Forbidden : {"error":{"message":"Forbidden"}}"). Checking captcha...
[22:28:13.237 +02:00 12 INF Tbot] [Test] Trying to solve captcha...
[22:28:13.491 +02:00 4 INF OGameD] [email] "ERRO [handlers.go:1398] failed to solve captcha (404 Not Found)"`

Seems like ogame ninja is also down

**Comment by biejay** [comment]
Same here! Can not login ....

**Comment by jumanjimanji** [comment]
Same problem!

**Comment by NoobOnTour024** [comment]
same. When then navigating to host:port/bot/captcha most of the time i dont get the window to enter 0,1,2, or 3 to select correct image.
Application then crashes: 

 `Unhandled exception. TBot.Ogame.Infrastructure.Exceptions.OgamedException: An error has occurred
   at TBot.Ogame.Infrastructure.OgameService.ManageResponse[T](HttpResponseMessage response) in /home/runner/work/TBot/TBot/TBot.Ogame.Infrastructure/OgameService.cs:line 254
   at TBot.Ogame.Infrastructure.OgameService.PostAsync[T](String resource, KeyValuePair`2[] parameters) in /home/runner/work/TBot/TBot/TBot.Ogame.Infrastructure/OgameService.cs:line 303
   at TBot.Ogame.Infrastructure.OgameService.SolveCaptcha(String challengeID, Int32 answer) in /home/runner/work/TBot/TBot/TBot.Ogame.Infrastructure/OgameService.cs:line 327
   at Tbot.Services.TBotMain.ResolveCaptcha() in /home/runner/work/TBot/TBot/TBot/Services/TBotMain.cs:line 205
   at Tbot.Services.TBotMain.Init(String settingPath, String alias, ITelegramMessenger telegramHandler) in /home/runner/work/TBot/TBot/TBot/Services/TBotMain.cs:line 249
   at Tbot.Services.InstanceManager.StartTBotMain(String settingsPath, String alias) in /home/runner/work/TBot/TBot/TBot/Services/InstanceManager.cs:line 255
   at Tbot.Services.InstanceManager.OnSettingsChanged() in /home/runner/work/TBot/TBot/TBot/Services/InstanceManager.cs:line 157
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()`

**Comment by LooOOooM** [comment]
Is this think here finally dead since capture ?
