### ISSUE TITLE
SleepMode throwing Errors

### ISSUE THREAD

**Issue by dustin-we** [ogame-tbot/TBot#198]
Hi,

When using SleepMode, I get these Errors:

`An error has occurred while handling sleep mode: Time-out interval must be less than 2^32-2. (Parameter 'dueTime') Stacktrace:    at System.Threading.Timer.Change(Int64 dueTime, Int64 period) at Tbot.Services.TBotMain.HandleSleepModeAsync(Object state) in /home/runner/work/TBot/TBot/TBot/Services/TBotMain.cs:line 1240 Next check at 01/01/0001 01:01:37`

To me, it looks like something time-related seems to be not working correctly. But I cant find a fix.
Is happening to a friend of mine as well.

Running on Windows 11.

Thank you!

**Comment by dustin-we** [comment]
Sorry, pressed enter a little to soon.

When using SleepMode, I get these Errors:

`An error has occurred while handling sleep mode: Time-out interval must be less than 2^32-2. (Parameter 'dueTime')
Stacktrace:    at System.Threading.Timer.Change(Int64 dueTime, Int64 period)
   at Tbot.Services.TBotMain.HandleSleepModeAsync(Object state) in /home/runner/work/TBot/TBot/TBot/Services/TBotMain.cs:line 1240
Next check at 01/01/0001 01:01:37`

To me, it looks like something time-related seems to be not working correctly. But I cant find a fix.
Is happening to a friend of mine as well.

Running on Windows 11.

Thank you!

**Comment by Markdotjames** [comment]
I have the same issue, latest server (UK)

**Comment by 0xE232FE** [comment]
OGame v12 changed html. You can find the latest version with fixes here until the Upstream will be updated.
https://github.com/0xE232FE/TBot/releases/tag/v3.0.4-v12-1

**Comment by Markdotjames** [comment]
that fixed it for me, Thank You!
