### ISSUE TITLE
InvalidOperationException crashing TBot

### ISSUE THREAD

**Issue by MrBurrBurr** [ogame-tbot/TBot#22]
Not sure if the stacktrace is enough for you to fix the issue. Let me know if I can help in any way.

```
[Info] [Brain] [10/09/2021 02:58:39] - Sending LargeCargo: 119;  with M:0 C:3,270,348 D:1,631,989 E:0 DM:0 from XXX [M:0:0:0] to XXX [P:0:0:0]
[Info] [FleetScheduler] [10/09/2021 02:58:39] - Sending fleet from [M:0:0:0] to [P:0:0:0]. Mission: Transport. Speed: 100% . Ships: LargeCargo: 119;
ERRO [ogame.go:2422] Get "https://s178-en.ogame.gameforge.com/game/index.php?component=movement&page=ingame": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
ERRO [ogame.go:2422] Get "https://s178-en.ogame.gameforge.com/game/index.php?component=movement&page=ingame": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Tbot.Program.AutoResearch(Object state)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
Aborted
```

**Comment by MrBurrBurr** [comment]
Yes, latest version.

And also yes, I have some connection issues. I was just not sure if the exception was a result of it.

**Comment by kokiddp** [comment]
this is most likely the reason
