### ISSUE TITLE
AutoColonize issue when Compute Techno not reserched

### ISSUE THREAD

**Issue by Daeloran** [ogame-tbot/TBot#71]
Hello,

I just realized that the autocolonize bug if we haven't researched computer technology at least level 1.

Here is the error I get:

`[09:51:08|Info|FleetScheduler] Sending fleet from [P:4:487:10] to [P:4:487:6]. Mission: Colonize. Speed: 100% Ships: ColonyShip: 1;
[09:51:08|Debug|FleetScheduler] Calculated flight time (one-way): 00:31:06
[09:51:08|Debug|FleetScheduler] Calculated flight time (full trip): 01:02:12
[09:51:08|Debug|FleetScheduler] Calculated flight fuel: 118
[09:51:08|Warning|FleetScheduler] Unable to send fleet, no slots available
[09:51:08|Info|Colonize] Delaying...
[09:51:08|Info|Brain] Repatriating resources...
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable1 source)
   at Tbot.Program.HandleColonize(Object state)
   at System.Threading.TimerQueueTimer.<>c.<.cctor>b__23_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
PS D:\Downloads\TBot>`

After this error, Tbot exit.

TBot version: 0.2.57.0
OS:  Windows 11
Runtime : .Net 5 latest

Thank you
Daeloran
[settings_copy.txt](https://github.com/ogame-tbot/TBot/files/9266787/settings_copy.txt)

**Comment by kokiddp** [comment]
fixed in v0.2.58
