### ISSUE TITLE
failed to find all resource settings

### ISSUE THREAD

**Issue by thstorm** [ogame-tbot/TBot#90]
Hi,

i am always getting the following error when running Tbot:

```
[16:56:16|Info|Brain] Running AutoMine on Helgoland [P:1:484:1]
[16:56:16|Debug|Tbot] Exception: An error has occurred: Status: error - Message: failed to find all resource settings
[16:56:16|Warning|Tbot] Stacktrace:    at Tbot.Services.OgamedService.GetResourceSettings(Planet planet)
   at Tbot.Program.UpdatePlanet(Celestial planet, UpdateTypes UpdateTypes)
[16:56:16|Warning|Tbot] An error has occurred. Skipping update
```

Any suggestions how to fix?

Here is my settings.json

```
{
	"Credentials": {
		"Universe": "XXX",
		"Email": "XXX",
		"Password": "XXX",
		"Language": "de",
		"LobbyPioneers": false,
		"BasicAuth": {
			"Username": "",
			"Password": ""
		}
	},
	"General": {
		"UserAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36",
		"Host": "192.168.3.3",
		"Port": "8282",
		"Proxy": {
			"Enabled": false,
			"Address": "",
			"Type": "socks5",
			"Username": "",
			"Password": "",
			"LoginOnly": true
		},
		"CaptchaAPIKey": "",
		"CookiesPath": "cookies.txt",
		"CustomTitle": "",
		"SlotsToLeaveFree": 1
	},
	"SleepMode": {
		"Active": true,
		"GoToSleep": "23:15",
		"WakeUp": "07:05",
		"PreventIfThereAreFleets": true,
		"TelegramMessenger": {
			"Active": false
		},
		"AutoFleetSave": {
			"Active": true,
			"OnlyMoons": true,
			"ForceUnsafe": true,
			"DeutToLeave": 200000,
			"Recall": true,
			"DefaultMission": "Deploy"
		}
	},
	"Defender": {
		"Active": true,
		"CheckIntervalMin": 1,
		"CheckIntervalMax": 22,
		"IgnoreProbes": true,
		"IgnoreMissiles": true,
		"IgnoreWeakAttack": false,
		"WeakAttackRatio": 3,
		"Autofleet": {
			"Active": true,
			"TelegramMessenger": {
				"Active": true
			}
		},
		"WhiteList": [
			100000,
			100003,
			100004
		],
		"SpyAttacker": {
			"Active": true,
			"Probes": 20
		},
		"MessageAttacker": {
			"Active": false,
			"Messages": [
				"hey",
				"hello",
				"i'm online'"
			]
		},
		"TelegramMessenger": {
			"Active": false
		},
		"Alarm": {
			"Active": true
		}
	},
	"Brain": {
		"Active": true,
		"AutoMine": {
			"Active": true,
			"MaxMetalMine": 40,
			"MaxCrystalMine": 35,
			"MaxDeuteriumSynthetizer": 37,
			"MaxSolarPlant": 20,
			"MaxFusionReactor": 20,
			"MaxMetalStorage": 13,
			"MaxCrystalStorage": 12,
			"MaxDeuteriumTank": 11,
			"MaxRoboticsFactory": 10,
			"MaxShipyard": 12,
			"MaxResearchLab": 12,
			"MaxMissileSilo": 0,
			"MaxNaniteFactory": 7,
			"MaxTerraformer": 8,
			"MaxSpaceDock": 7,
			"MaxLunarBase": 8,
			"MaxLunarShipyard": 0,
			"MaxLunarRoboticsFactory": 8,
			"MaxSensorPhalanx": 6,
			"MaxJumpGate": 1,
			"Transports": {
				"Active": false,
				"CargoType": "SmallCargo",
				"DeutToLeave": 1000000,
				"RoundResources": true,
				"Origin": {
					"Galaxy": 3,
					"System": 333,
					"Position": 8,
					"Type": "Moon"
				}
			},
			"RandomOrder": true,
			"Exclude": [
				{
					"Galaxy": 3,
					"System": 333,
					"Position": 15,
					"Type": "Planet"
				}
			],
			"OptimizeForStart": true,
			"PrioritizeRobotsAndNanites": false,
			"BuildDepositIfFull": false,
			"DepositHours": 6,
			"MaxDaysOfInvestmentReturn": 7,
			"DeutToLeaveOnMoons": 1000000,
			"CheckIntervalMin": 10,
			"CheckIntervalMax": 20
		},
		"AutoResearch": {
			"Active": true,
			"MaxEnergyTechnology": 20,
			"MaxLaserTechnology": 12,
			"MaxIonTechnology": 5,
			"MaxHyperspaceTechnology": 20,
			"MaxPlasmaTechnology": 20,
			"MaxCombustionDrive": 19,
			"MaxImpulseDrive": 17,
			"MaxHyperspaceDrive": 15,
			"MaxEspionageTechnology": 8,
			"MaxComputerTechnology": 20,
			"MaxAstrophysics": 23,
			"MaxIntergalacticResearchNetwork": 12,
			"MaxWeaponsTechnology": 25,
			"MaxShieldingTechnology": 25,
			"MaxArmourTechnology": 25,
			"Target": {
				"Galaxy": 3,
				"System": 333,
				"Position": 8,
				"Type": "Planet"
			},
			"Transports": {
				"Active": false,
				"CargoType": "SmallCargo",
				"DeutToLeave": 1000000,
				"RoundResources": true,
				"Origin": {
					"Galaxy": 3,
					"System": 333,
					"Position": 8,
					"Type": "Moon"
				}
			},
			"OptimizeForStart": true,
			"EnsureExpoSlots": true,
			"PrioritizeAstrophysics": true,
			"PrioritizePlasmaTechnology": true,
			"PrioritizeEnergyTechnology": true,
			"PrioritizeIntergalacticResearchNetwork": true,
			"CheckIntervalMin": 10,
			"CheckIntervalMax": 20
		},
		"AutoCargo": {
			"Active": false,
			"ExcludeMoons": true,
			"CargoType": "LargeCargo",
			"RandomOrder": true,
			"MaxCargosToBuild": 50,
			"MaxCargosToKeep": 50,
			"LimitToCapacity": true,
			"SkipIfIncomingTransport": true,
			"Exclude": [
				{
					"Galaxy": 3,
					"System": 333,
					"Position": 15,
					"Type": "Moon"
				}
			],
			"CheckIntervalMin": 60,
			"CheckIntervalMax": 240
		},
		"AutoRepatriate": {
			"Active": false,
			"ExcludeMoons": false,
			"MinimumResources": 1000000,
			"LeaveDeut": {
				"OnlyOnMoons": true,
				"DeutToLeave": 1000000
			},
			"Target": {
				"Galaxy": 5,
				"System": 63,
				"Position": 8,
				"Type": "Moon"
			},
			"CargoType": "LargeCargo",
			"RandomOrder": true,
			"SkipIfIncomingTransport": true,
			"Exclude": [
				{
					"Galaxy": 3,
					"System": 333,
					"Position": 15,
					"Type": "Planet"
				}
			],
			"CheckIntervalMin": 30,
			"CheckIntervalMax": 60
		},
		"BuyOfferOfTheDay": {
			"Active": false,
			"CheckIntervalMin": 240,
			"CheckIntervalMax": 360
		}
	},
	"Expeditions": {
		"Active": true,
		"PrimaryShip": "LargeCargo",
		"MinPrimaryToSend": 1,
		"PrimaryToKeep": 20,
		"SecondaryShip": "Null",
		"MinSecondaryToSend": 0,
		"SecondaryToPrimaryRatio": 2,
		"ManualShips": {
			"Active": false,
			"Ships": {
				"LargeCargo": 1300,
				"LightFighter": 26000,
				"Reaper": 1,
				"Pathfinder": 1,
				"EspionageProbe": 1
			}
		},
		"WaitForAllExpeditions": false,
		"WaitForMajorityOfExpeditions": false,
		"SplitExpeditionsBetweenSystems": {
			"Active": true,
			"Range": 1
		},
		"RandomizeOrder": true,
		"FuelToCarry": 20000,
		"Origin": [
			{
				"Galaxy": 1,
				"System": 484,
				"Position": 8,
				"Type": "Planet"
			}
		]
	},
	"AutoFarm": {
		"Active": false,
		"ExcludeMoons": true,
		"ScanRange": [
			{
				"Galaxy": 2,
				"StartSystem": 360,
				"EndSystem": 420
			}
		],
		"Exclude": [
			{
				"Galaxy": 3,
				"System": 3,
				"Planet": 3
			}
		],
		"KeepReportFor": 180,
		"NumProbes": 10,
		"Origin": [
			{
				"Galaxy": 2,
				"System": 396,
				"Position": 4,
				"Type": "Planet"
			}
		],
		"TargetsProbedBeforeAttack": 30,
		"CargoType": "LargeCargo",
		"FleetSpeed": 100,
		"MinCargosToKeep": 0,
		"MinCargosToSend": 25,
		"CargoSurplusPercentage": 10,
		"BuildCargos": false,
		"BuildProbes": false,
		"MinimumResources": 1000000,
		"MinimumPlayerRank": 500,
		"MaxFlightTime": 7200,
		"MaxWaitTime": 7200,
		"MinLootFuelRatio": 0.5,
		"PreferedResource": "",
		"SlotsToLeaveFree": 1,
		"CheckIntervalMin": 30,
		"CheckIntervalMax": 60
	},
	"AutoHarvest": {
		"Active": true,
		"HarvestOwnDF": true,
		"HarvestDeepSpace": true,
		"MinimumResourcesOwnDF": 300,
		"MinimumResourcesDeepSpace": 50000,
		"CheckIntervalMin": 30,
		"CheckIntervalMax": 60
	},
	"AutoColonize": {
		"Active": false,
		"Origin": {
			"Galaxy": 5,
			"System": 64,
			"Position": 8,
			"Type": "Planet"
		},
		"SlotsToLeaveFree": 0,
		"Targets": [
			{
				"Galaxy": 6,
				"System": 1,
				"Position": 8
			},
			{
				"Galaxy": 6,
				"System": 1,
				"Position": 9
			}
		],
		"CheckIntervalMin": 30,
		"CheckIntervalMax": 60
	},
	"TelegramMessenger": {
		"Active": true,
		"API": "XXX",
		"ChatId": "XXX",
		"TelegramAutoPing": {
			"Active": true,
			"EveryHours":  1
		}
	}
}

```

**Comment by kokiddp** [comment]
closing

**Comment by NmC** [comment]
I'm getting same error at v0.2.62 am i missing something?

<img width="852" alt="image" src="https://user-images.githubusercontent.com/357177/191961654-291b5660-e36c-4b8d-8e62-71459f313960.png">
